### ISSUE TITLE
Group by Creature Source

### ISSUE THREAD

**Issue by ThorvaldtM** [DrZed/Magic-Legends-DPS-Tracker#1]
I believe it would make more sense to group attacks by creature. This would allow to judge the power of each card.

I wanted to contribute to the project but I haven't done java in a very long time and could not get JavaFX to work with OpenJDK.

**Comment by DrZed** [comment]
You need OpenJFX if you wanna use OpenJDK, I use Oracle JDK (the creators of Java)

**Comment by DrZed** [comment]
![image](https://user-images.githubusercontent.com/5124544/113494208-3ccca200-94b4-11eb-817c-6c890e6a9804.png)
how's this look for seeing pets and their damage?

**Comment by ThorvaldtM** [comment]
I am confused by your screenshot :D

I was thinking something like this :

Source | Ability | Base DMG | DPH | Hits
------------ | ------------- | ------------- | ------------- | -------------
Gryphon | Melee Attack | 123456 | 123456 | 1
Gryphon | Gale | 123456 | 123456 | 1
null  | Molten Shell | 123456 | 123456 | 1
Emberling | Melee Attack | 123456 | 123456 | 1

And as an options, we could have group by source or group by Ability (this would merge all the lines that belongs to same category)

I tried OpenJFX but I was getting 
`Error: JavaFX runtime components are missing, and are required to run this application`
and couldn't solve the issue so I gave up.

**Comment by DrZed** [comment]
Just use the EXE version of vx.x release
