### ISSUE TITLE
Feature Request: add a way to choose encounter

### ISSUE THREAD

**Issue by luxkun** [DrZed/Magic-Legends-DPS-Tracker#12]
Right now the app just resets all the data when a new encounter is started. It would be nice to have a way to view the data of a previous encounter.
(maybe a list of encounter with the time it started/ended that you can choose from)

**Comment by DrZed** [comment]
Working on re-opening older encounters

**Comment by DrZed** [comment]
Legit all I gotta do is add it to drop down, and Load the encounter as a "Config" via my API
Framework added if you want to pull, and test to ensure it actually renders it properly or want to write the picker yourself

I'm off to bed @luxkun

**Comment by DrZed** [comment]
https://user-images.githubusercontent.com/5124544/113637909-ad55f900-9643-11eb-88c3-8a0543cb6542.mp4

Done didly
