### ISSUE TITLE
Improve speed to parsing for previously created logs

### ISSUE THREAD

**Issue by luxkun** [DrZed/Magic-Legends-DPS-Tracker#14]
Right now this is terribly slow, it took a few minutes to load a log that included about 4 dungeon runs.

**Comment by DrZed** [comment]
You can just set guiPollRate=15, to 1 or even 0

**Comment by DrZed** [comment]
0 would poll as fast as your CPU can handle anyway. I did go ahead and implement your iterator, albeit I had to nerf it a bit due to JavaFX thread getting starved causing Orphaned thread exception
