### ISSUE TITLE
Non-ASCII characters are not properly displayed

### ISSUE THREAD

**Issue by JonathanSamelson** [DrZed/Magic-Legends-DPS-Tracker#16]
Hi,

Thank you for your nice tool! 

Here's a screenshot of the app when the game is in French.
Would it be possible to support other languages characters ? 

![image](https://user-images.githubusercontent.com/19322574/114222133-7ac33d80-996e-11eb-813b-7a49eab411ba.png)

**Comment by DrZed** [comment]
New Version coming tonight
https://user-images.githubusercontent.com/5124544/114662927-83e24080-9cc7-11eb-827f-2a88cebd1b6e.mp4
