### ISSUE TITLE
"Wave of Radiance" is treated as an enemy 

### ISSUE THREAD

**Issue by luxkun** [DrZed/Magic-Legends-DPS-Tracker#3]
This is shown as an enemy instead of a player's skill (it's the Sanctifier's Q).
Log line:
`21:04:04:12:44:23.2::Lukian,P[100116@31218895 Lukian@Lukian#hiddenId],Wave of Radiance,C[762764 Ability_Sanctifier_Secondary_Caster],Nightfall Predator,C[762154 Inn_Gavony_Werewolves_Standard_Predator],Wave of Radiance,Pn.Y0tp2f1,Physical,Kill,77973.4,0`

**Comment by luxkun** [comment]
Still not fixed by https://github.com/DrZed/Magic-Legends-DPS-Tracker/commit/ddad524b75de13c02163010e14caca14ac276b78

I now see this as a green entity (friendly entity?)

**Comment by DrZed** [comment]
Even you can't read the game's log funny.
self , selfID, pet, petID, target, targetID, ability, abilityID,type ,flags, magnitude, magnitudeBase
A lot of abilities create entities.
Tornado for instance is an entity.
Another thing, COLORS DO NOT DICTATE ENEMIES
I Color Coded your own pets as Red originally, Green as other players, and Blue as their pets
If you read the config you would've seen that
