### ISSUE TITLE
Feature Request: add % of damage in the Abilities view

### ISSUE THREAD

**Issue by luxkun** [DrZed/Magic-Legends-DPS-Tracker#6]
I think it would be useful to see what % a specific ability has done.
The PIE is very useful but I would find it even more useful just having the raw % of each ability

**Comment by DrZed** [comment]
that's doable
tomorrows update may have

**Comment by DrZed** [comment]
That's harder considering that puts an extra step of math in the render code, damage share could be worth though

**Comment by DrZed** [comment]
![image](https://user-images.githubusercontent.com/5124544/113531557-1a5f8500-9597-11eb-9027-6316d0047433.png)
