### ISSUE TITLE
Crash on end encounter

### ISSUE THREAD

**Issue by luxkun** [DrZed/Magic-Legends-DPS-Tracker#8]
Happening with multiple logs, this is blocking me from using the tool pretty much.

Attaching error logs and parsed log file from the game.
[crashLogs.txt](https://github.com/DrZed/Magic-Legends-DPS-Tracker/files/6254631/crashLogs.txt)
[Combatlog_2021-04-04_11-00-00.Log](https://github.com/DrZed/Magic-Legends-DPS-Tracker/files/6254634/Combatlog_2021-04-04_11-00-00.Log)

This is how it looks after it breaks:
![image](https://user-images.githubusercontent.com/22868/113510748-283fe680-9554-11eb-9d68-231225e9b625.png)

EDIT: using latest from github

**Comment by DrZed** [comment]
Also fixed that, bad documentation on my part caused me to misuse my own library
