### ISSUE TITLE
Feature request: include all entities spawned/owned by the player inside the abilities list

### ISSUE THREAD

**Issue by luxkun** [DrZed/Magic-Legends-DPS-Tracker#9]
It would be really useful to have such a view to understanding how much each spawned entity is helping the Player's DPS.

For example in the following screenshot "Angel Token", in my mind, should be added to the PIE with all the damages the player has done, so I can understand how important is "Angel Token" in my build.
Same thing for "Soldier Illusion Token" and "Elemental Token"

![image](https://user-images.githubusercontent.com/22868/113511344-4c50f700-9557-11eb-84b9-ecda2b9ed2dd.png)

**Comment by DrZed** [comment]
done in 1.7
